
import { Language, MockSalesData, Pakkeshop, StoreProduct, ShopLookImage, DeliverySlot } from './types';

export const UI_TEXT = {
  da: {
    title: 'NORVOSS',
    subtitle: 'Din E-handels Intelligence Partner',
    nav_dashboard: 'Oversigt',
    nav_product: 'Produkt AI',
    nav_promo: 'Salg & Kampagner',
    nav_business: 'Forretningsværktøjer',
    nav_storefront: 'Min Butik (Live)',
    welcome: 'Velkommen tilbage',
    stats_revenue: 'Omsætning (30 dage)',
    stats_orders: 'Ordrer',
    stats_pending: 'Afventer',
    btn_generate: 'Generer Indhold',
    btn_analyze: 'Analyser Kampagner',
    label_product_name: 'Produktnavn',
    label_price: 'Pris (DKK)',
    label_upload: 'Upload Produktbillede',
    label_scan: 'Scan Etiket/Emballage (AI)',
    placeholder_chat: 'Skriv en besked...',
    loading: 'Arbejder...',
    promo_header: 'Kampagneforslag',
    prod_header: 'Bilingval Produktgenerator',
    compliance_warning: 'Husk altid 14 dages fortrydelsesret.',
    success_msg: 'Succes!',
    error_msg: 'Der opstod en fejl.',
    btn_back: 'Tilbage',
    // Auth
    auth_login_title: 'Log Ind',
    auth_signup_title: 'Opret Konto',
    auth_email: 'E-mailadresse',
    auth_password: 'Adgangskode',
    auth_fullname: 'Fulde Navn',
    auth_storename: 'Butiksnavn',
    auth_confirm_pass: 'Bekræft Adgangskode',
    auth_forgot: 'Glemt Adgangskode?',
    auth_btn_login: 'Log Ind',
    auth_btn_signup: 'Opret Konto',
    auth_switch_signup: 'Har du ikke en konto? Opret nu',
    auth_switch_login: 'Har du allerede en konto? Log Ind',
    auth_gdpr: 'Jeg accepterer Vilkårene og Privatlivspolitikken.',
    auth_pass_strength: 'Adgangskode Styrke:',
    auth_logout_success: 'Du er logget ud. På gensyn!',
    error_store_required: 'Butiksnavn er påkrævet',
    // Landing Page
    landing_hero: 'Slip din butik løs med Gemini AI.',
    landing_sub: 'Den alt-i-en e-handelsplatform til danske SMV\'er.',
    landing_cta_primary: 'Start Gratis Prøveperiode',
    landing_how_it_works: 'Sådan Fungerer Det',
    landing_feat_header: 'Power Your Store with Gemini AI',
    landing_feat_content: 'Automatiseret indhold',
    landing_feat_legal: 'Juridisk Compliance',
    landing_feat_forecast: 'Lagerprognose',
    landing_login: 'Log Ind',
    // Steps
    step_1_title: 'Opret Konto',
    step_1_desc: 'Tilmeld dig hurtigt og vælg dine butikspræferencer.',
    step_2_title: 'Upload & Generer',
    step_2_desc: 'Upload et produktbillede. Vores AI skriver beskrivelser på dansk og engelsk.',
    step_3_title: 'Tjek & Godkend',
    step_3_desc: 'Brug compliance-værktøjer til at sikre, at alt overholder EU-regler.',
    step_4_title: 'Sælg Globalt',
    step_4_desc: 'Publicer din butik live med integrerede betalinger og fragt.',
    // Storefront Specific
    hero_title: 'Slip din stil løs. Køb Fremtiden.',
    hero_subtitle: 'Høj energi, fedt design. Oplev den nye bølge af NORVOSS stil.',
    cta_buy: 'Udforsk Nu',
    cta_explore: 'Se Kollektionen',
    section_new: 'Nye Ankomster',
    section_popular: 'Mest Populære',
    section_shop_look: 'Shop Looket',
    usp_delivery: 'Lynhurtig Levering',
    usp_payment: 'Sikker MobilePay',
    usp_return: 'Nem Retur',
    usp_design: 'Dansk Kvalitet',
    footer_signup: 'Tilmeld dig nyhedsbrevet',
    footer_text: 'Få de vildeste tilbud først.',
    btn_subscribe: 'Tilmeld',
    search_placeholder: 'Søg efter noget fedt...',
    search_results: 'Resultater for',
    recommendations: 'Andre købte også',
    checkout_header: 'Kasse',
    checkout_pakkeshop: 'Vælg Pakkeshop',
    checkout_delivery_time: 'Vælg Leveringstidspunkt',
    checkout_mobilepay: 'Betal med MobilePay',
    checkout_success: 'Tak for din ordre!',
    checkout_notification: 'Ordrebekræftelse sendt på SMS.',
    // Checkout Multi-step
    checkout_step1: 'Leveringsdetaljer',
    checkout_step2: 'Forsendelsesmuligheder',
    checkout_step3: 'Betaling',
    label_fullname: 'Fulde Navn',
    label_email: 'E-mail',
    label_phone: 'Telefon (+45)',
    label_address: 'Adresse',
    label_zip: 'Postnummer',
    label_city: 'By',
    btn_continue_shipping: 'Fortsæt til Forsendelse',
    btn_continue_payment: 'Fortsæt til Betaling',
    btn_pay_now: 'Betal Nu',
    summary_header: 'Ordreoversigt',
    summary_subtotal: 'Subtotal',
    summary_shipping: 'Fragt',
    summary_total: 'Total',
    // Store Launch / URL
    url_active_title: 'Din Live Butiks-URL er Aktiv!',
    btn_copy: 'Kopier Link',
    msg_copied: 'Link Kopieret!',
    btn_launch: 'Udgiv Butik',
    launch_desc: 'Din butik er klar. Gå live nu!',
    // Business Tools
    tool_compliance: 'Juridisk Tjek',
    tool_pricing: 'Prisovervågning',
    tool_invoice: 'Fakturering',
    tool_social: 'Sociale Medier',
    tool_translator: 'B2B Oversætter',
    tool_coupons: 'Smart Kuponer',
    tool_fraud: 'Svindel Vagt',
    tool_forecast: 'Lager Prognose',
    tool_landing: 'Landing Page',
    tool_access: 'WCAG Tjek',
    tool_voice: 'Stemmekontrol',
    tool_chatbot: 'Bilingual Chatbot',
    tool_search: 'Smart Search',
    compliance_placeholder: 'Indsæt din returpolitik eller produkttekst her...',
    btn_check_compliance: 'Tjek Lovlighed',
    compliance_pass: 'Godkendt',
    compliance_fail: 'Problemer Fundet',
    invoice_title: 'Faktura #DK-2025-001',
    invoice_customer: 'Kunde',
    invoice_total: 'Total inkl. Moms',
    reviews_summary: 'AI Resumé af Anmeldelser',
    pros: 'Fordele',
    cons: 'Ulemper',
    social_placeholder: 'Indsæt kundebesked (f.eks. "Hvornår kommer varen igen?")...',
    translate_placeholder: 'Indsæt tekst til oversættelse...',
    coupon_generate: 'Generer Rednings-Kupon',
    coupon_cart_value: 'Indkøbskurv Værdi',
    translate_btn: 'Oversæt',
    fraud_analyze_btn: 'Analyser Transaktion',
    forecast_btn: 'Generer Prognose',
    landing_placeholder: 'Mål for kampagne (f.eks. "Udsalg på kontorstole")',
    landing_btn: 'Generer Side',
    access_placeholder: 'Indsæt HTML-kode her...',
    access_btn: 'Tjek Acessibility',
    tool_netlify: 'Netlify Styring',
    netlify_sites: 'Dine Netlify Sider',
    netlify_btn_fetch: 'Hent Sider',
    netlify_no_sites: 'Ingen sider fundet eller token mangler.',
    netlify_site_name: 'Sidenavn',
    netlify_site_url: 'URL',
    netlify_site_created: 'Oprettet',
    netlify_status: 'Status',
    voice_listening: 'Lytter...',
    voice_btn: 'Start Kommando',
    // Product Hub
    prod_tab_list: 'Produktliste',
    prod_tab_create: 'Opret/Rediger Produkt',
    prod_table_img: 'Billede',
    prod_table_name: 'Navn',
    prod_table_price: 'Pris',
    prod_table_stock: 'Lager',
    prod_table_status: 'Status',
    prod_table_actions: 'Handlinger',
    btn_edit: 'Rediger',
    btn_delete: 'Slet',
    btn_save: 'Gem Ændringer',
    btn_client_preview: 'Kundevisning',
    // Financial & Metrics
    metric_invoiced: 'Faktureret I Alt',
    metric_balance: 'Nuværende Saldo',
    metric_due: 'Próximo Vencimento',
    metric_coupons: 'Udstedte Kuponer',
    metric_redemption: 'Indløsningsrate',
    metric_na: 'Ingen forfaldne',
  },
  en: {
    title: 'NORVOSS',
    subtitle: 'Your E-commerce Intelligence Partner',
    nav_dashboard: 'Dashboard',
    nav_product: 'Product AI',
    nav_promo: 'Sales & Promos',
    nav_business: 'Business Tools',
    nav_storefront: 'My Store (Live)',
    welcome: 'Welcome back',
    stats_revenue: 'Revenue (30 days)',
    stats_orders: 'Orders',
    stats_pending: 'Pending',
    btn_generate: 'Generate Content',
    btn_analyze: 'Analyze Campaigns',
    label_product_name: 'Product Name',
    label_price: 'Price (DKK)',
    label_upload: 'Upload Product Image',
    label_scan: 'Scan Label/Package (AI)',
    placeholder_chat: 'Type a message...',
    loading: 'Working...',
    promo_header: 'Campaign Suggestions',
    prod_header: 'Bilingual Product Generator',
    compliance_warning: 'Always remember the 14-day cooling-off period.',
    success_msg: 'Success!',
    error_msg: 'An error occurred.',
    btn_back: 'Back',
    // Auth
    auth_login_title: 'Sign In',
    auth_signup_title: 'Create Account',
    auth_email: 'Email Address',
    auth_password: 'Password',
    auth_fullname: 'Full Name',
    auth_storename: 'Store Name',
    auth_confirm_pass: 'Confirm Password',
    auth_forgot: 'Forgot Password?',
    auth_btn_login: 'Sign In',
    auth_btn_signup: 'Create Account',
    auth_switch_signup: "Don't have an account? Sign Up",
    auth_switch_login: 'Already have an account? Sign In',
    auth_gdpr: 'I accept the Terms and Privacy Policy.',
    auth_pass_strength: 'Password Strength:',
    auth_logout_success: 'You have been successfully signed out. See you soon!',
    error_store_required: 'Store Name is required',
    // Landing Page
    landing_hero: 'Unleash Your Store with Gemini AI.',
    landing_sub: 'The all-in-one e-commerce platform for Danish SMBs.',
    landing_cta_primary: 'Start Your Free Trial Now',
    landing_how_it_works: 'How It Works',
    landing_feat_header: 'Power Your Store with Gemini AI',
    landing_feat_content: 'Automated Content',
    landing_feat_legal: 'Legal Compliance',
    landing_feat_forecast: 'Inventory Forecast',
    landing_login: 'Sign In',
    // Steps
    step_1_title: 'Create Account',
    step_1_desc: 'Sign up quickly and select your store preferences.',
    step_2_title: 'Upload & Generate',
    step_2_desc: 'Upload a product image. Our AI writes descriptions in Danish & English.',
    step_3_title: 'Check & Approve',
    step_3_desc: 'Use compliance tools to ensure everything meets EU regulations.',
    step_4_title: 'Sell Globally',
    step_4_desc: 'Publish your live store with integrated payments and shipping.',
    // Storefront Specific
    hero_title: 'Unleash Your Style. Shop the Future.',
    hero_subtitle: 'High energy, bold design. Experience the new wave of NORVOSS style.',
    cta_buy: 'Explore Now',
    cta_explore: 'View Collection',
    section_new: 'New Arrivals',
    section_popular: 'Most Popular',
    section_shop_look: 'Shop the Look',
    usp_delivery: 'Lightning Delivery',
    usp_payment: 'Secure MobilePay',
    usp_return: 'Easy Returns',
    usp_design: 'Danish Quality',
    footer_signup: 'Sign up for our newsletter',
    footer_text: 'Get the hottest deals first.',
    btn_subscribe: 'Subscribe',
    search_placeholder: 'Search for something cool...',
    search_results: 'Search Results for',
    recommendations: 'Others also bought',
    checkout_header: 'Checkout',
    checkout_pakkeshop: 'Select Pakkeshop',
    checkout_delivery_time: 'Select Delivery Time',
    checkout_mobilepay: 'Pay with MobilePay',
    checkout_success: 'Thank you for your order!',
    checkout_notification: 'Order confirmation sent via SMS.',
    // Checkout Multi-step
    checkout_step1: 'Delivery Details',
    checkout_step2: 'Shipping Options',
    checkout_step3: 'Payment',
    label_fullname: 'Full Name',
    label_email: 'Email Address',
    label_phone: 'Phone (+45)',
    label_address: 'Street Address',
    label_zip: 'Zip Code',
    label_city: 'City',
    btn_continue_shipping: 'Continue to Shipping',
    btn_continue_payment: 'Continue to Payment',
    btn_pay_now: 'Pay Now',
    summary_header: 'Order Summary',
    summary_subtotal: 'Subtotal',
    summary_shipping: 'Shipping',
    summary_total: 'Total',
    // Store Launch / URL
    url_active_title: 'Your Live Store URL is Active!',
    btn_copy: 'Copy Link',
    msg_copied: 'Link Copied!',
    btn_launch: 'Launch Store',
    launch_desc: 'Your store is ready. Go live now!',
    // Business Tools
    tool_compliance: 'Legal Check',
    tool_pricing: 'Price Monitoring',
    tool_invoice: 'Invoicing',
    tool_social: 'Social Media',
    tool_translator: 'B2B Translator',
    tool_coupons: 'Smart Coupons',
    tool_fraud: 'Fraud Shield',
    tool_forecast: 'Forecaster',
    tool_landing: 'Landing Page',
    tool_access: 'WCAG Audit',
    tool_voice: 'Voice Control',
    tool_chatbot: 'Bilingual Chatbot',
    tool_search: 'Smart Search',
    compliance_placeholder: 'Paste your return policy or product text here...',
    btn_check_compliance: 'Check Compliance',
    compliance_pass: 'Compliant',
    compliance_fail: 'Issues Found',
    invoice_title: 'Invoice #DK-2025-001',
    invoice_customer: 'Customer',
    invoice_total: 'Total inkl. Moms',
    reviews_summary: 'AI Review Summary',
    pros: 'Pros',
    cons: 'Cons',
    social_placeholder: 'Paste customer message (e.g. "When is item back?")...',
    translate_placeholder: 'Paste text to translate...',
    coupon_generate: 'Generate Rescue Coupon',
    coupon_cart_value: 'Cart Value',
    translate_btn: 'Translate',
    fraud_analyze_btn: 'Analyze Transaction',
    forecast_btn: 'Generate Forecast',
    landing_placeholder: 'Campaign Goal (e.g. "Office Chair Sale")',
    landing_btn: 'Generate Page',
    access_placeholder: 'Paste HTML code here...',
    access_btn: 'Audit Accessibility',
    tool_netlify: 'Netlify Management',
    netlify_sites: 'Your Netlify Sites',
    netlify_btn_fetch: 'Fetch Sites',
    netlify_no_sites: 'No sites found or token missing.',
    netlify_site_name: 'Site Name',
    netlify_site_url: 'URL',
    netlify_site_created: 'Created',
    netlify_status: 'Status',
    voice_listening: 'Listening...',
    voice_btn: 'Start Command',
    // Product Hub
    prod_tab_list: 'Product List',
    prod_tab_create: 'Create/Edit Product',
    prod_table_img: 'Image',
    prod_table_name: 'Name',
    prod_table_price: 'Price',
    prod_table_stock: 'Stock',
    prod_table_status: 'Status',
    prod_table_actions: 'Actions',
    btn_edit: 'Edit',
    btn_delete: 'Delete',
    btn_save: 'Save Changes',
    btn_client_preview: 'Client Preview',
    // Financial & Metrics
    metric_invoiced: 'Total Invoiced',
    metric_balance: 'Current Balance',
    metric_due: 'Next Due Date',
    metric_coupons: 'Coupons Issued',
    metric_redemption: 'Redemption Rate',
    metric_na: 'No Invoice Due',
  }
};

// CLEAN START: Empty Inventory
export const MOCK_INVENTORY: MockSalesData[] = [];

// CLEAN START: Zero Stats with Neutral Change
export const MOCK_STATS = [
  { label_en: 'Revenue', label_da: 'Omsætning', value: '0.00 DKK', change: '--%' },
  { label_en: 'Active Carts', label_da: 'Aktive Kurve', value: '0', change: '--%' },
  { label_en: 'Returns', label_da: 'Returvarer', value: '0.0%', change: '--%' },
];

export const MOCK_PAKKESHOPS: Pakkeshop[] = [
  { id: '1', name: 'Føtex Vesterbro', address: 'Vesterbrogade 74, 1620 København', distance: '150m', carrier: 'PostNord' },
  { id: '2', name: 'Kiosk Kiosken', address: 'Istedgade 12, 1650 København', distance: '300m', carrier: 'GLS' },
  { id: '3', name: 'Meny Frederiksberg', address: 'Gammel Kongevej 102, 1850 Frederiksberg', distance: '650m', carrier: 'PostNord' },
];

// CLEAN START: Empty Products
export const MOCK_PRODUCTS: StoreProduct[] = [];

export const MOCK_SHOP_LOOK: ShopLookImage = {
  id: 1,
  title: 'NORVOSS Living Room',
  imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?auto=format&fit=crop&q=80&w=1200',
  items: []
};

export const MOCK_DELIVERY_SLOTS: DeliverySlot[] = [
  { id: 'slot1', date: 'Tomorrow', time: '10:00 - 14:00', cost: '49 DKK' },
  { id: 'slot2', date: 'Tomorrow', time: '18:00 - 20:00 (Evening)', cost: '69 DKK' },
  { id: 'slot3', date: 'Day after tomorrow', time: '10:00 - 14:00', cost: '39 DKK' },
];

// CLEAN START: Generic Transaction Data (No User PII)
export const MOCK_TRANSACTION = {
  id: 'TXN-0000',
  amount: 0,
  currency: 'DKK',
  ip_country: 'DK', 
  card_country: 'DK',
  shipping_address: '',
  customer_email: '' 
};
